// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MekanoBilling(arg1, arg2) {
  return window['go']['main']['App']['MekanoBilling'](arg1, arg2);
}

export function MekanoPayment(arg1) {
  return window['go']['main']['App']['MekanoPayment'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}
