// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mekano} from '../models';

export function MekanoBilling(arg1:string,arg2:string):Promise<mekano.BillingStatistics>;

export function MekanoPayment(arg1:string):Promise<mekano.PaymentStatistics>;

export function OpenFile():Promise<string>;
